# Generated by Django 5.2.9 on 2026-01-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Official title of the case', max_length=255)),
                ('case_number', models.CharField(help_text='Official case number', max_length=100, unique=True)),
                ('court', models.CharField(help_text='Court where the case is being heard', max_length=255)),
                ('date_of_judgment', models.DateField(blank=True, help_text='Date when the judgment was delivered', null=True)),
                ('parties_involved', models.TextField(help_text='Details of the parties involved in the case')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the case', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('FACTS', 'Facts'), ('ISSUES', 'Issues'), ('ARGUMENTS', 'Arguments'), ('JUDGMENT', 'Judgment'), ('REASONING', 'Reasoning')], help_text='Type of the case section', max_length=20)),
                ('content', models.TextField(help_text='Content of the case section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cases.legalcase')),
            ],
        ),
    ]
