# Generated by Django 5.2.9 on 2026-01-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded legal document file', upload_to='legal_documents/')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the document for analysis', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether text extraction is completed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.legalcase')),
            ],
        ),
    ]
